version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: schedule_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: University_db
    ports:
      # ВАЖНО: слева порт твоего ноута (5433), справа порт внутри контейнера (5432)
      - "5433:5432"
    volumes:
      # Сохраняем данные БД физически на диске, чтобы они не удалились при остановке контейнера
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
